### PR TITLE
fix: publish under cdklabs

### PR DESCRIPTION
**Pull request by rix0rrr**
This package used to be published under `@aws-cdk`, but it is not owned by the CDK team (yet). Publishing under the `@aws-cdk` namespace without an `-alpha` suffix will raise undue support expectations on the wrong team.

Publish under `@cdklabs` instead.

### CODE REVIEW

**Review by mrgrain — APPROVED** [review]

**Comment by vlesierse** [comment]
Hi @rix0rrr, can't we mark the package as experimental with the `-alpha` suffix instead? I prefer this construct be listed like `aws-lambda-nodejs`, `aws-lambda-python`, `aws-lambda-go`

@mrgrain what do you think?

**Comment by vlesierse** [comment]
Sure it make sense when we are not working towards a CDK team supported version of the construct. Think that some direction is needed, how far these type of convenience wrapper constructs will be supported. I know that there are initiatives of other languages that have the same question.

**Comment by rix0rrr** [comment]
After talking it over internally, we will leave the situation as-is. Since .NET is a supported CDK language, it makes sense that we'd have an `aws-lambda-dotnet` construct that we support (even though we might rely on you to make most of the technical decisions).

In that case, the `@aws-cdk` namespace is appropriate.

**Comment by vlesierse** [comment]
Thank you @rix0rrr, of course I'm fully supportive of this decision but I think it is good to have these types of conversations.

**Pull request closed without merging**
